---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[chinachu::default]
    attributes:
